name: Automation Runner (GitHub Actions)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  newman:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Create .env file
        run: |
          echo "POSTGRES_USER=postgres" >> .env
          echo "POSTGRES_PASSWORD=postgres" >> .env
          echo "POSTGRES_DB=todo_db" >> .env
          echo "DATABASE_URL=postgresql://postgres:postgres@db:5432/todo_db" >> .env
          echo "CORS_ORIGINS=http://localhost:3000,http://localhost:8000" >> .env
      
      - name: Build and start services with Docker Compose
        run: docker-compose up -d
      
      - name: Wait for services to be ready
        run: |
          echo "Waiting for backend to be ready..."
          timeout 60 bash -c 'until curl -f http://localhost:8000/docs > /dev/null 2>&1; do sleep 2; done'
          echo "Backend is ready!"
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      
      - name: Install Newman
        run: npm install -g newman
      
      - name: Run Postman collection
        run: newman run 'tests/Todo Backend (FastAPI).postman_collection.json' --env-var "baseUrl=http://localhost:8000"
      
      - name: Show logs on failure
        if: failure()
        run: docker-compose logs
      
      - name: Stop services
        if: always()
        run: docker-compose down -v
